django/mysite/blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'

urlpatterns = [ 
        path('', views.IndexView.as_view(), name='index'),
        path('sign_in/', views.SignInView.as_view(), name='sign_in'),
        path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
        path('post_list/', views.BlogView.as_view(), name='post_list'),
        path('post_create/', views.PostCreate.as_view(), name='post_create'),
        path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
        path('<int:pk>/post_edit/', views.PostEdit.as_view(), name='post_edit'),
        path('<int:pk>/post_delete/', views.PostDelete.as_view(), name='post_delete'),
        path('login/', auth_views.LoginView.as_view(template_name='blog/sign_in.html')),
        path('logout/', views.LogoutView.as_view(), name='logout' ),
        ]
        

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
        path('polls/', include('polls.urls')),
        path('user/', include('user.urls')),
        path('blog/', include('blog.urls')),
        path('admin/', admin.site.urls),
]

django/mysite/blog/models.py
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, AbstractUser, User


#class BaseUserManager(BaseUserManager):
#    def create_user(self):
#    def create_superuser(self):
#        )

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    main = models.CharField(max_length = 1000)
    create_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

class MyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100) 


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        print("create\n")

django/mysite/blog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
                'password' : forms.PasswordInput(),
                }
        
class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        
        if commit:
            user.save()
        return user

django/mysite/blog/views.py
from django.shortcuts import render,redirect

from django.views import generic

from django.urls import reverse_lazy

from django.utils import timezone

from django.contrib.auth import logout, login, authenticate

#from .models import Post, User
from .models import Post

from .forms import UserForm, NewUserForm
# Create your views here.

class LogoutView(generic.base.View):
    def get(self, request):
        logout(request)
        return redirect('blog:index')

#class IndexView(generic.base.TemplateResponseMixin, generic.base.View):
class IndexView(generic.TemplateView):
#    model = User
    template_name = 'blog/index.html'
#    context_object_name = "user_list"    
#    def get(self,request):
#        if request.user.is_authenticated:
#            print("login\n")
#        else :
#            print("logout\n")
#
#        return render(request, self.template_name)
class SignInView(generic.FormView):
    form_class = UserForm
    template_name = 'blog/sign_in.html'
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username = username, password = password)
        if user is not None:
            print("login")
            login(request = request, user = user)
        return redirect("blog:index")

class SignUpView(generic.FormView):
    form_class = NewUserForm
    template_name = 'blog/sign_up.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    success_url = "/blog/"
class BlogView(generic.ListView):
    model = Post
    template_name = 'blog/post_list.html'
    
    #def get_queryset(self):
    #    print(Post.objects.count())
    #    return Post.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.all();
        return context

class PostEdit(generic.edit.UpdateView):
    model = Post
    fields = ['title']
    template_name = 'blog/post_create.html'
    success_url = reverse_lazy('blog:index')

class PostDelete(generic.edit.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

class PostDetail(generic.DetailView):
    # set model of this view
    model = Post
    # set template name of this view
    template_name = 'blog/post_detail.html'
    # set return query name
    context_object_name = 'post_detail'

    def get_object(self):
        print(Post.objects.get(pk=self.kwargs['pk']))
        return Post.objects.get(pk=self.kwargs['pk'])


    #def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    context['post_detail'] = Post.objects.get(pk=self.kwargs['pk'])
    #    print(self.object.pk)
    #    return context

class PostCreate(generic.edit.CreateView):
    model = Post
    template_name = 'blog/post_create.html'

    fields = ['title', 'main']
    success_url = reverse_lazy('blog:post_list')
    def post(self, request):
        title = request.POST['title']
        main = request.POST['main']
        
        post = Post(title=title, main=main)
        post.save()

        return redirect('blog:post_list')
#    def post(self, request) :
#        return redirect('blog:index')
        

django/mysite/blog/templates/blog/index.html
<a href="{% url 'blog:sign_in' %}">sign in</a>

<a href="{% url 'blog:logout' %}">logout</a>

<a href="{% url 'blog:post_list' %}">post list</a>

<a href="{% url 'blog:sign_up' %}">sign_up</a>

{% if user_list %}
<ul>
    {% for u in user_list %}
    <li>
        {{ u.user_id }}
    </li>
    {% endfor %}
</ul> 
{% else %}
{% endif %}

{% if user.is_authenticated %}
  <div>exist user session</div> 
{% endif %}

django/mysite/blog/templates/blog/post_create.html
<form action="" method ="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="add"'>
</form>

django/mysite/blog/templates/blog/post_detail.html
<h1>POST DETAIl</h1>


<p1>{{ post_detail.title }}</p1>
<p1>{{ post_detail.main }}</p1>
<p1>{{ post_detail.create_date }}</p1>

<a href="{% url 'blog:post_edit' post_detail.id  %}">Edit</a>
<a href="{% url 'blog:post_delete' post_detail.id  %}">Delete/a>

django/mysite/blog/templates/blog/post_list.html
<h1>POST</h1>

<ul>
    {% for p in post %}
    <li>
        <a href="{% url 'blog:post_detail' p.id %}">{{ p.title }} {{ p.create_date }}</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'blog:post_create'  %}">post create</a>

django/mysite/blog/templates/blog/sign_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title></title>
</head>
<body>
    <form action="" method ="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add">
    </form>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    
</body>
</html>

<!--
    <form class="form-signin">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form> -->

django/mysite/blog/templates/blog/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title></title>
</head>
<body>
    <form action="" method ="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add">
    </form>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    
</body>
</html>

<!--
    <form class="form-signin">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form> -->