django/mysite/blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'

urlpatterns = [ 
        path('', views.IndexView.as_view(), name='index'),
        path('sign_in/', views.SignInView.as_view(), name='sign_in'),
        path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
        path('post_list/', views.BlogView.as_view(), name='post_list'),
        path('post_create/', views.PostCreate.as_view(), name='post_create'),
        path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
        path('<int:pk>/post_edit/', views.PostEdit.as_view(), name='post_edit'),
        path('<int:pk>/post_delete/', views.PostDelete.as_view(), name='post_delete'),
        path('login/', auth_views.LoginView.as_view(template_name='blog/sign_in.html')),
        path('logout/', views.LogoutView.as_view(), name='logout' ),
        ]
        

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
        path('polls/', include('polls.urls')),
        path('user/', include('user.urls')),
        path('blog/', include('blog.urls')),
        path('admin/', admin.site.urls),
]

django/mysite/user/urls.py
from django.urls import path


from . import views

app_name = 'user'

urlpatterns = [ 
        path('', views.IndexView.as_view(), name='index'),
        path('login/', views.LoginView.as_view(), name='login'),
        path('signup/', views.SignUpView.as_view(), name='signup'),
        path('result/', views.ResultView.as_view(), name='result'),
        #path('login/', views.login, name='login'),
        ]

django/mysite/user/models.py
from django.db import models

class User(models.Model):
    user_id = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    address = models.CharField(max_length = 200, default = "")
    email = models.EmailField(max_length = 100, default = "")
    create_date = models.DateTimeField("create date")

    def __str__(self):
        return self.user_id
# Create your models here.

django/mysite/user/forms.py
from django import forms

from .models import User

class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['user_id', 'password', 'address' , 'email']


class LoginForm(forms.ModelForm):
    #user_id = forms.CharField(label='user_id', max_length=30)
    #password = forms.CharField(label='password', max_length=30)
    class Meta:
        model = User
        fields = ['user_id', 'password']

django/mysite/user/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import FormView
from django.urls import reverse

from django.contrib.auth.hashers import make_password, check_password
from .models import User
from .forms import LoginForm, SignUpForm

class IndexView(generic.TemplateView):
    template_name = 'user/index.html'
    #context_object_name = 'user_name_list'

class SignUpView(FormView):
    form_class = SignUpForm
    template_name = 'user/signup.html'

    def post(self, request):
        user_id = request.POST['user_id']
        password = request.POST['password']
        
        user = User(user_id = user_id , password=make_password(password))
        user.save()
        return redirect('user:index')
        
class LoginView(FormView):
    form_class = LoginForm
    template_name = 'user/login.html'
    
    def post(self, request) :
        user_id = request.POST['user_id']
        password = request.POST['password']
        try: 
            user = User.objects.get(user_id=user_id)
            if check_password(password, user.password) :
                request.session['user_id'] = user_id
                return redirect('user:result')
        except User.DoesNotExist:
            user = None
        
        
        return redirect('user:login')
    def form_valid(self, form):
        return super().form_valid(form)

#    def get_queryset(self):
#        return User.objects.all()
#def login(request):
#    if request.method == "POST":
#        form = LoginForm(request.POST)
#        user_id = request.POST['user_id']
#        password = request.POST['password']
#        #user = authenticate(user_id = user_id, password = password)
#        #if user is not None :
#        #    login()
#        return redirect('user:index')
#        #return render(request, 'user/index.html', {'form': form})
#    else :
#        form = LoginForm()
#        return render(request, 'user/login.html', {'form': form})

class ResultView(generic.TemplateView):
    template_name = 'user/result.html'

django/mysite/user/templates/user/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            <h1>Djang User</h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

django/mysite/user/templates/user/index.html
{% extends 'user/base.html' %}

{% block content %}
<h2>LOGIN</h2>
    {{ form.as_p }}
<form method="post" action="">
    {% csrf_token %}
    <button type="button" onclick="location.href='{% url 'user:login' %}' ">login page</button>
    <button type="button" onclick="location.href='{% url 'user:signup' %}' ">singup page</button>
</form>
{% endblock %}

django/mysite/user/templates/user/login.html
{% extends 'user/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

django/mysite/user/templates/user/result.html
{{ request.session.user_id }}
{{ request.session.password }}

django/mysite/user/templates/user/signup.html
{% extends 'user/base.html' %}

{% block content %}
<html>
<head></head>
<body>


<h1>SignUp</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='Sign up'>
</form>

<input type="text" id="sample4_postcode" placeholder="우편번호" readonly >
<input type="button" onclick="sample4_execDaumPostcode()" value="우편번호 찾기"><br>
<input type="text" id="sample4_roadAddress" placeholder="도로명주소" readonly>
<input type="text" id="sample4_jibunAddress" placeholder="지번주소" readonly>
<span id="guide" style="color:#999;display:none"></span>
<input type="text" id="sample4_detailAddress" placeholder="상세주소">
<input type="text" id="sample4_extraAddress" placeholder="참고항목">

<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.
    function sample4_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var roadAddr = data.roadAddress; // 도로명 주소 변수
                var extraRoadAddr = ''; // 참고 항목 변수

                // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                    extraRoadAddr += data.bname;
                }
                // 건물명이 있고, 공동주택일 경우 추가한다.
                if(data.buildingName !== '' && data.apartment === 'Y'){
                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                }
                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                if(extraRoadAddr !== ''){
                    extraRoadAddr = ' (' + extraRoadAddr + ')';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample4_postcode').value = data.zonecode;
                document.getElementById("sample4_roadAddress").value = roadAddr;
                document.getElementById("sample4_jibunAddress").value = data.jibunAddress;
                
                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.
                if(roadAddr !== ''){
                    document.getElementById("sample4_extraAddress").value = extraRoadAddr;
                } else {
                    document.getElementById("sample4_extraAddress").value = '';
                }

                var guideTextBox = document.getElementById("guide");
                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.
                if(data.autoRoadAddress) {
                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;
                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';
                    guideTextBox.style.display = 'block';

                } else if(data.autoJibunAddress) {
                    var expJibunAddr = data.autoJibunAddress;
                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';
                    guideTextBox.style.display = 'block';
                } else {
                    guideTextBox.innerHTML = '';
                    guideTextBox.style.display = 'none';
                }
            }
        }).open();
    }
</script>
</body>
</html>
{% endblock %}